<?php
use Livewire\Volt\Component;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;
use Illuminate\Support\Facades\DB;

new #[Layout('components.layouts.humanresource')] #[Title('Regional Wage Orders')] class extends Component
{
 public $region_code='', $region_name='', $wage_order_code='', $effective_from='', $effective_until='', $daily_minimum_wage='', $hourly_minimum_wage='', $classification='', $source_url='';
 public function save(){ \App\Support\PeopleAccess::hr(); $d=$this->validate(['region_code'=>'required|max:30','region_name'=>'required|max:150','wage_order_code'=>'required|max:60','effective_from'=>'required|date','effective_until'=>'nullable|date|after_or_equal:effective_from','daily_minimum_wage'=>'required|numeric|min:0','hourly_minimum_wage'=>'nullable|numeric|min:0','classification'=>'nullable|max:100','source_url'=>'nullable|url|max:500']); DB::table('regional_wage_orders')->insert(array_merge($d,['created_at'=>now(),'updated_at'=>now()])); $this->reset(['region_code','region_name','wage_order_code','effective_from','effective_until','daily_minimum_wage','hourly_minimum_wage','classification','source_url']); session()->flash('success','Wage order added.'); }
 public function getOrdersProperty(){ return DB::table('regional_wage_orders')->orderByDesc('effective_from')->orderBy('region_name')->get(); }
}
?>
<div class="p-6 md:p-8"><div class="mb-6"><h1 class="text-2xl font-bold">Regional Wage Orders</h1><p class="text-sm text-gray-600">Effective-dated regional minimum-wage records. Verify source material before marking a rule operational.</p></div>@if(session('success'))<div class="mb-4 p-3 rounded bg-green-50 text-green-800">{{ session('success') }}</div>@endif<div class="bg-white border rounded-xl p-5 mb-6"><h2 class="font-semibold mb-4">Add wage order</h2><div class="grid md:grid-cols-3 gap-4">@foreach([['region_code','Region code'],['region_name','Region name'],['wage_order_code','Wage order'],['effective_from','Effective from'],['effective_until','Effective until'],['daily_minimum_wage','Daily minimum wage'],['hourly_minimum_wage','Hourly minimum wage'],['classification','Classification'],['source_url','Official source URL']] as $f)<div><label class="form-label">{{ $f[1] }}</label><input type="{{ str_contains($f[0],'date')?'date':(str_contains($f[0],'wage')?'number':'text') }}" step="0.01" wire:model="{{ $f[0] }}" class="form-input"></div>@endforeach</div><button wire:click="save" class="btn-primary mt-4">Add wage order</button></div><div class="bg-white border rounded-xl p-5 overflow-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-gray-500"><th class="py-2">Region</th><th>Order</th><th>Effective</th><th>Daily</th><th>Hourly</th></tr></thead><tbody>@foreach($this->orders as $o)<tr class="border-t"><td class="py-2">{{ $o->region_name }} ({{ $o->region_code }})</td><td>{{ $o->wage_order_code }}</td><td>{{ $o->effective_from }}</td><td>₱{{ number_format($o->daily_minimum_wage,2) }}</td><td>{{ $o->hourly_minimum_wage ? '₱'.number_format($o->hourly_minimum_wage,2) : '—' }}</td></tr>@endforeach</tbody></table></div></div>
