<x-layouts.humanresource title="Approval Center">
<div class="space-y-6">
<div><h1 class="text-2xl font-semibold">Approval Center</h1><p class="text-sm opacity-70">One queue for routine HR approvals.</p></div>
<div class="grid grid-cols-2 md:grid-cols-4 gap-3">
@foreach([['Leave',$leave->count()],['Overtime',$overtime->count()],['Attendance',$attendance->count()],['Employee requests',$requests->count()]] as $card)<div class="rounded-xl border p-4"><div class="text-sm opacity-70">{{ $card[0] }}</div><div class="text-2xl font-semibold">{{ $card[1] }}</div></div>@endforeach
</div>
<section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Pending leave</h2>@forelse($leave as $r)<div class="p-4 border-b"><b>{{ $r->full_name }}</b> · {{ $r->start_date }} → {{ $r->end_date }}<div class="text-sm opacity-70">{{ $r->reason }}</div></div>@empty<div class="p-4 opacity-70">None.</div>@endforelse</section>
<section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Pending overtime</h2>@forelse($overtime as $r)<div class="p-4 border-b"><b>{{ $r->full_name }}</b> · {{ $r->starts_at }} → {{ $r->ends_at }} · {{ $r->minutes }} min<div class="text-sm opacity-70">{{ $r->reason }}</div></div>@empty<div class="p-4 opacity-70">None.</div>@endforelse</section>
<section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Attendance corrections</h2>@forelse($attendance as $r)<div class="p-4 border-b"><b>{{ $r->full_name }}</b> · {{ $r->attendance_date }}<div class="text-sm opacity-70">{{ $r->reason }}</div></div>@empty<div class="p-4 opacity-70">None.</div>@endforelse</section>
<section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Employee requests</h2>@forelse($requests as $r)<div class="p-4 border-b flex justify-between gap-3"><div><b>{{ $r->full_name }}</b> · {{ str_replace('_',' ',ucfirst($r->type)) }}<div class="text-sm opacity-70">{{ $r->details }}</div></div><div class="flex gap-2"><form method="post" action="{{ route('hr.operations.request.decision',$r->id) }}">@csrf<input type="hidden" name="status" value="approved"><button class="rounded-lg border px-3 py-2 text-sm">Approve</button></form><form method="post" action="{{ route('hr.operations.request.decision',$r->id) }}">@csrf<input type="hidden" name="status" value="rejected"><button class="rounded-lg border px-3 py-2 text-sm">Reject</button></form></div></div>@empty<div class="p-4 opacity-70">None.</div>@endforelse</section>
</div></x-layouts.humanresource>
