<x-layouts.humanresource title="Employee 360">
<div class="space-y-6">
 <div class="rounded-xl border p-5"><div class="flex flex-col md:flex-row md:justify-between gap-3"><div><h1 class="text-2xl font-semibold">{{ $employee->full_name }}</h1><p class="opacity-70">{{ $employee->job_title }} · {{ $employee->department_name ?: 'No department' }}</p></div><div class="text-sm">Status: <strong>{{ ucfirst($employee->status) }}</strong><br>Pay basis: <strong>{{ ucfirst($employee->pay_basis ?? 'monthly') }}</strong></div></div></div>
 <div class="grid gap-4 md:grid-cols-4">@foreach([['Salary','₱'.number_format($employee->salary,2)],['Region',$employee->work_region ?: 'Not set'],['SSS',$employee->sss_number ?: '—'],['TIN',$employee->tin ?: '—']] as $c)<div class="rounded-xl border p-4"><div class="text-xs uppercase opacity-60">{{ $c[0] }}</div><div class="mt-2 font-medium">{{ $c[1] }}</div></div>@endforeach</div>
 <div class="grid gap-6 lg:grid-cols-2">
  <section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Payroll history</h2>@forelse($payroll as $p)<div class="p-3 border-b flex justify-between"><span>{{ $p->period_start }} → {{ $p->period_end }}</span><span>₱{{ number_format($p->net_pay,2) }} · {{ ucfirst($p->status) }}</span></div>@empty<div class="p-4 opacity-70">No payroll records.</div>@endforelse</section>
  <section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Salary history</h2>@forelse($salaryHistory as $s)<div class="p-3 border-b flex justify-between"><span>{{ $s->effective_from }}<br><small class="opacity-60">{{ $s->reason }}</small></span><span>₱{{ number_format($s->salary,2) }}</span></div>@empty<div class="p-4 opacity-70">No recorded salary changes yet.</div>@endforelse</section>
  <section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Recent attendance</h2>@forelse($attendance as $a)<div class="p-3 border-b flex justify-between"><span>{{ $a->date }}</span><span>{{ ucfirst($a->status) }}</span></div>@empty<div class="p-4 opacity-70">No attendance records.</div>@endforelse</section>
  <section class="rounded-xl border overflow-hidden"><h2 class="p-4 font-semibold border-b">Leave history</h2>@forelse($leave as $l)<div class="p-3 border-b flex justify-between"><span>{{ $l->start_date }} → {{ $l->end_date }}</span><span>{{ ucfirst($l->status) }}</span></div>@empty<div class="p-4 opacity-70">No leave records.</div>@endforelse</section>
 </div>
</div>
<div class="bg-white rounded-xl shadow p-6 mt-6"><h2 class="font-semibold mb-4">Record Lifecycle Event</h2><form method="POST" action="{{ route('hr.operations.employee.lifecycle',$employee->employee_id) }}" class="grid md:grid-cols-4 gap-3">@csrf<select name="event_type" class="rounded-lg border-gray-300"><option>onboarding</option><option>probation</option><option>promotion</option><option>transfer</option><option>salary_change</option><option>separation</option><option>rehire</option></select><input type="date" name="effective_date" required class="rounded-lg border-gray-300"><input name="details" placeholder="Details" class="rounded-lg border-gray-300"><button class="rounded-lg bg-gray-900 text-white px-4">Record</button></form></div>
</x-layouts.humanresource>
