<x-layouts.humanresource :title="'Payroll Approval'">
<div class="p-6 md:p-8 max-w-7xl mx-auto space-y-6">
@if(session('success'))<div class="rounded-lg bg-green-50 text-green-800 px-4 py-3">{{ session('success') }}</div>@endif
@if(session('error'))<div class="rounded-lg bg-red-50 text-red-800 px-4 py-3">{{ session('error') }}</div>@endif
<div><h1 class="text-2xl font-bold">Payroll Approval & Locking</h1><p class="text-gray-500">{{ $period->start }} – {{ $period->end }}</p></div>
<div class="grid md:grid-cols-5 gap-4">@foreach([['Employees',$summary['eligible']],['Calculated',$summary['calculated']],['Approved',$summary['approved']],['Paid',$summary['paid']],['Issues',count($summary['issues'])]] as $card)<div class="bg-white rounded-xl shadow p-5"><div class="text-sm text-gray-500">{{ $card[0] }}</div><div class="text-2xl font-bold">{{ $card[1] }}</div></div>@endforeach</div>
<div class="bg-white rounded-xl shadow p-6"><h2 class="font-semibold mb-4">Workflow</h2><div class="flex flex-wrap gap-3"><span class="px-3 py-2 rounded-full bg-gray-100">1. Validate</span><span class="px-3 py-2 rounded-full bg-gray-100">2. Calculate</span><span class="px-3 py-2 rounded-full {{ $summary['approved']?'bg-green-100':'bg-gray-100' }}">3. Approve</span><span class="px-3 py-2 rounded-full {{ $summary['paid']?'bg-green-100':'bg-gray-100' }}">4. Pay</span><span class="px-3 py-2 rounded-full {{ $control->status==='locked'?'bg-green-100':'bg-gray-100' }}">5. Lock</span></div></div>
<div class="bg-white rounded-xl shadow p-6"><h2 class="font-semibold mb-4">Exceptions</h2>@forelse($summary['issues'] as $i)<div class="py-3 border-b"><b>{{ strtoupper($i['level']) }}</b> — {{ $i['label'] }} ({{ $i['count'] }})</div>@empty<div class="text-green-700">No control-center issues.</div>@endforelse</div>
<div class="flex gap-3"><form method="POST" action="{{ route('hr.operations.payroll.approve') }}">@csrf<input type="hidden" name="period" value="{{ $period->start }}"><button class="px-4 py-2 bg-gray-900 text-white rounded-lg" {{ $summary['issues']||$summary['calculated']===0?'disabled':'' }}>Approve Payroll</button></form><form method="POST" action="{{ route('hr.operations.payroll.paid') }}">@csrf<input type="hidden" name="period" value="{{ $period->start }}"><button class="px-4 py-2 bg-green-700 text-white rounded-lg">Mark Paid</button></form></div>
</div></x-layouts.humanresource>
